function rd2winadcp(fname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% read ADCP binary file in the form of WINADCP export mat file.
%written by JHPARK 2016 Dec1
%
%output variables: AnBIT AnDepthmm AnH100thDeg AnOrienUP AnP100thDeg AnR100thDeg AnT100thDeg RDIBin1Mid RDIBinSize RDIPingsPerEns RDISecPerPing RDISystem SerBins SerC1cnt SerC2cnt SerC3cnt SerC4cnt SerCAcnt SerDay SerEA1cnt SerEA2cnt SerEA3cnt SerEA4cnt SerEAAcnt SerEmmpersec SerErmmpersec SerHour SerMin SerMon SerNmmpersec SerPG1 SerPG2 SerPG3 SerPG4 SerSec SerVmmpersec SerYear

%time series variables:header={'AnBIT','AnDepthmm','AnH100thDeg','AnOrienUP',...
%     'AnP100thDeg','AnR100thDeg','AnT100thDeg',...
%     'SerC1cnt','SerC2cnt','SerC3cnt','SerC4cnt','SerCAcnt',...
%     'SerDay','SerEA1cnt','SerEA2cnt','SerEA3cnt','SerEA4cnt','SerEAAcnt',...
%     'SerEmmpersec','SerErmmpersec','SerHour','SerMin','SerMon',...
%     'SerNmmpersec',...
%     'SerPG1','SerPG2','SerPG3','SerPG4','SerSec','SerVmmpersec','SerYear'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

m2mm=1000;
[adcp,cfg,ens]=rd_adcp( fname);
times=datevec(adcp.mtime);
% header={'AnBatt', 'AnBIT','AnDepthmm', 'AnH100thDeg', 'AnOrienUP', 'AnP100thDeg', 'AnR100thDeg', 'AnT100thDeg',...   'RDIBin1Mid', 'RDIBinSize',     'RDIEnsDate', 'RDIEnsInterval', 'RDIEnsTime', 'RDIFileName', 'RDIPingsPerEns', 'RDISecPerPing', 'RDISystem', 'SerBins', 'SerC1cnt', 'SerC2cnt', 'SerC3cnt', 'SerC4cnt', 'SerCAcnt', 'SerDay', 'SerDir10thDeg', 'SerEA1cnt', 'SerEA2cnt', 'SerEA3cnt', 'SerEA4cnt', 'SerEAAcnt', 'SerEmmpersec', 'SerEnsembles', 'SerErmmpersec', 'SerHour', 'SerHund', 'SerMagmmpersec', 'SerMin', 'SerMon', 'SerNmmpersec', 'SerPG1', 'SerPG2', 'SerPG3', 'SerPG4', 'SerSec', 'SerVmmpersec', 'SerYear'};

header={ 'AnBIT',...
    'AnDepthmm', 'AnH100thDeg', 'AnOrienUP', 'AnP100thDeg', 'AnR100thDeg', 'AnT100thDeg',...
    'RDIBin1Mid', 'RDIBinSize',...
    'RDIPingsPerEns', 'RDISecPerPing', 'RDISystem',...
    'SerBins', 'SerC1cnt', 'SerC2cnt', 'SerC3cnt', 'SerC4cnt', 'SerCAcnt',...
    'SerDay', 'SerEA1cnt', 'SerEA2cnt', 'SerEA3cnt', 'SerEA4cnt', 'SerEAAcnt', ...
    'SerEmmpersec', 'SerErmmpersec', 'SerHour', 'SerMin', 'SerMon', 'SerNmmpersec',...
    'SerPG1', 'SerPG2', 'SerPG3', 'SerPG4',...
    'SerSec', 'SerVmmpersec', 'SerYear'};

headerw={'adcp.ok',...
    'adcp.pressure', 'ahdg', 'adcp.orientation', 'apit', 'arol', 'atemp',...
    'adcp.config.bin1_dist', 'adcp.config.cell_size',...
    ' cfg.pings_per_ensemble', 'cfg.time_between_ping_groups', '[adcp.config.name num2str(adcp.config.beam_freq)]',...
    '[1:adcp.config.n_cells]', ' squeeze(adcp.corr(:,1,:))', 'squeeze(adcp.corr(:,2,:))', 'squeeze(adcp.corr(:,3,:))', 'squeeze(adcp.corr(:,4,:))', 'squeeze(nanmean(adcp.corr,2))',...
    'times(:,3)''', 'squeeze(adcp.intens(:,1,:))', 'squeeze(adcp.intens(:,2,:))', 'squeeze(adcp.intens(:,3,:))', 'squeeze(adcp.intens(:,4,:))', 'squeeze(nanmean(adcp.intens,2))',...
    'auu', 'aerr', 'times(:,4)''', 'times(:,5)''', 'times(:,2)''', 'avv', ...
    'squeeze(adcp.percent(:,1,:))', 'squeeze(adcp.percent(:,2,:))', 'squeeze(adcp.percent(:,3,:))', 'squeeze(adcp.percent(:,4,:))',...
    'times(:,6)''', 'averti', 'times(:,1)'''};

ahdg=adcp.heading;
id8=find(ahdg>180);
ahdg(id8)=ahdg(id8)-360;
ahdg=ahdg*100;

apit=adcp.pitch*100;
arol=adcp.roll*100;
atemp=adcp.temperature*100;

auu=adcp.east_vel*m2mm;
aerr=adcp.error_vel*m2mm;
avv=adcp.north_vel*m2mm;
averti=adcp.vert_vel*m2mm;

yy=int2str(times(:,1));
times(:,1)=str2num(yy(:,3:4));

for ii=1:length(headerw)
    eval([header{ii} '=' headerw{ii} ''';'])
end

RDISystem=RDISystem';
% clearex AnBIT AnDepthmm AnH100thDeg AnOrienUP AnP100thDeg AnR100thDeg AnT100thDeg RDIBin1Mid RDIBinSize RDIPingsPerEns RDISecPerPing RDISystem SerBins SerC1cnt SerC2cnt SerC3cnt SerC4cnt SerCAcnt SerDay SerEA1cnt SerEA2cnt SerEA3cnt SerEA4cnt SerEAAcnt SerEmmpersec SerErmmpersec SerHour SerMin SerMon SerNmmpersec SerPG1 SerPG2 SerPG3 SerPG4 SerSec SerVmmpersec SerYear

for ii=1:length(header)
    eval(['assignin(''base'',[header{ii}],' header{ii} ');' ]);
end

end
